sonar.projectKey=resume-service
sonar.projectName=resume-service
sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.host.url=http://sonarqube:9000
