name: SonarCloud (branch fin)

on:
  push:
    branches:
      - fin
  pull_request:
    branches:
      - fin

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarcloud:
    name: Build + SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important pour branches/PR

      # ------------------------
      # 1) BACKEND (Spring Boot / Maven)
      # --------------------------
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Build + tests (tu peux mettre -DskipTests si tu veux)
      - name: Build Backend (resume-service)
        working-directory: backend/resume-service
        run: mvn -B clean package -DskipTests


      # -----------------------
      # 2) FRONTEND (Node)
      # IMPORTANT: ton vrai frontend est dans frontend/resume-ui
      # ----------------------------
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/resume-ui/package-lock.json

      - name: Build Frontend (resume-ui)
        working-directory: frontend/resume-ui
        run: |
            npm ci
            npm run build || true


      # ---------------------------
      # 3) FASTAPI (Python) - optionnel
      # -------------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install FastAPI deps (optional)
        working-directory: ai-matching-fast-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pytest -q  # si tu ajoutes des tests

      # ----------------------------
      # 4) SONARCLOUD SCAN
      # ----------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=oudaoudfarha
            -Dsonar.projectKey=OudaoudFarha_ai-matching
            -Dsonar.sources=backend/resume-service/src,ai-matching-fast-api,frontend/resume-ui/src
            -Dsonar.exclusions=**/node_modules/**,**/target/**,**/.venv/**,**/__pycache__/**,**/dist/**,**/build/**
            -Dsonar.java.binaries=backend/resume-service/target/classes
            -Dsonar.branch.name=fin
